# Site settings
author: veslie l
title: Learning Programing Online 
header-img: img/home-bg.png
email: veslielosius@yahoo.com
copyright_name: veslie l
description: > # this means to ignore newlines until "baseurl:"
  Stressed out Programmers
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  veslie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
